# Generated by Django 4.2.30 on 2026-06-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technomom', '0002_product_size_alter_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_stock',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
